### ISSUE TITLE
Add support for prometheus authentication token/basic auth

### ISSUE THREAD

**Issue by uberspot** [thought-machine/prometheus-cardinality-exporter#14]
Would be good if the exporter supported authentication token/basic auth for prometheus. 
Some prometheus instances are auth'ed by default so the exporter won't work with them.

Should just be adding a header like: `Authorization:Bearer $ACCESS_TOKEN` and loading the access token from an env var/file.

**Comment by luke-richardson** [comment]
Hi Paul,

Thank you for the feature request, we would be happy to add this. I'll take this to our next review meeting and get it prioritised in our backlog.

Thanks!

**Comment by harryfallows** [comment]
@uberspot 

Hi Paul,

I am currently working on this ticket, would you mind specifying for me whether you are using the exporter with the --service_discovery or --proms option?

Thanks,
Harry

**Comment by uberspot** [comment]
Nice, :) 
Yup i've tried both options and stuck with --proms at the end.

**Comment by harryfallows** [comment]
@uberspot 

Hi Paul,

I have submitted a PR for this issue (#15). I think it should solve the problem, however, my implementation is slightly different to what you suggested. Instead of reading the access token from a var file, it reads the whole Authorization header value. This was done to allow different Authorization types (e.g. Bearer & Basic). Let me know if this works for you, and any other comments/issues/questions about the PR.

Thanks,
Harry

**Comment by uberspot** [comment]
Had a quick peek, looks good :) I'm happy to test it out on our clusters once it's merged/released.

**Comment by harryfallows** [comment]
Sorry for the delay, the PR has been merged.

**Comment by RichardoC** [comment]
You can get this functionality with docker image tag c070a26a219baa26cd87a55f1ef5952f13aba968 or digest: sha256:1c2b4b7894b8ef3f30181efaba12722bb4a8a487aa5c1f36ef1bb6380c8c6452

**Comment by uberspot** [comment]
So I tested this on an openshift k8s cluster and the exporter complains about:
```
time="2021-08-18T14:07:55Z" level=info msg="Obtaining metics from prometheus instances specified as arguments."
time="2021-08-18T14:07:55Z" level=info msg="Serving on port: 9090"
time="2021-08-18T14:07:55Z" level=info msg="Serving Prometheus metrics on /metrics"
time="2021-08-18T14:07:55Z" level=info msg="Starting Prometheus cardinality metric collection."
time="2021-08-18T14:07:55Z" level=info msg="Fetching current Prometheus status, from Prometheus instance: prometheus-k8s-openshift-monitoring. Sharded instance: prometheus-k8s-openshift-monitoring. Namespace: apps."
time="2021-08-18T14:07:58Z" level=warning msg="Error fetching Prometheus status: Can't parse json: invalid character '<' looking for beginning of value" error="Can't parse json: invalid character '<' looking for beginning of value"

```
I'm specifying the prometheus instance directly with --proms=https://....internal_cluster_url....:port 

I've constructed the k8s secret correctly (based on k8s/secret.yaml) and have verified that the auth file is there in the directory and have included the same "Bearer ....." string in all 3 variations progressively. aka namespace, namespace_instance, namespace_instance_shard. All variations complain with the same error, which I presume is that the page returns a webpage instead and doesn't authenticate to the API. 


The thing is I also exec'ed in the pod and tried: 
```
export BEARER="someSecretToken"

wget --no-check-certificate -O - --header="Authorization: Bearer ${BEARER}" https://internal_cluster_url:port/api/v1/status/tsdb
```
And that works fine, so the token is 100% correct. And if it wasn't I'd expect an auth/403 error anyway.

Can we add verbose logging to be able to debug these sort of issues? And print all requests perhaps? 
Any other ideas what this could be?

**Comment by harryfallows** [comment]
Can you verify that with the `--proms=https://....internal_cluster_url....:port` option, your authorisation yaml/secrets file has a variable in the following format:
`"https://....internal_cluster_url....:port": "Bearer 123456789"`
For example, your secret.yaml looks like this:
```
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-cardinality-exporter-secret
  namespace: example-namespace
stringData:
  prometheus-api-auth-values.yaml: |
    "https://....internal_cluster_url....:port": "Bearer 123456789"
```
It is essential that the key for the auth mapping is identical to the `--proms` value.

**Comment by uberspot** [comment]
Hi Harry, yeah the secret has the identical URL in the same format you added. Copy pasted it from `--proms=...`

**Comment by harryfallows** [comment]
I have added logs for the status of the response from the prometheus API, as well as support for logging levels with the "--log.level" flag (e.g. --log.level=debug) in #17. Feel free to add additional debug logs if you wish, and I can review them.
